3rdparty/eventuals-grpc

bazel/deps.bzl

grpc pulls incompatible versions of absl and boring ssl this commit
frontruns the dependency chain, loading compatible version to allow
compilation on linux with gcc and clang.

Change deps.bzl and bazelrc for grpc to build on linux

---

bazel/repos.bzl

In order to make use of bazel/repos.bzl in other projects the file must
explicitly declare the repo com_github_3rdparty_stout_grpc.

Declare com_github_3rdparty_stout_grpc externally

---

BUILD.bazel
test/BUILD.bazel

Before this PR, our `BUILD.bazel` files were not auto-formatted.
This PR uses `buildifier` (analogous to `prettier`, `gofmt`, etc.) to auto-format the `BUILD.bazel` files in this repo. There are no functional changes, only formatting.

Auto-format Bazel files using standard 'buildifier' tool

---

.bazelrc
.gitignore
test/BUILD.bazel
test/streaming.cc

Before this PR, `test/streaming.cc` was a single large monolithic test that would not allow us to test multiple different client behaviors easily. 
This PR leaves the test functionally identical, but factors out the code that produces the client behavior (which the next commit will introduce various versions of) from the framework of the test (which will not change). It also splits `streaming.cc` into a separate `cc_test` target, so that it can be built and tested in isolation more easily, for faster write/test-iteration.
As a bonus, adds a `.gitignore` file to this repo, and sets some flags helpful for debugging in the `.bazelrc`.

Refactor streaming test

---

stout/grpc/client.h
test/streaming.cc

Before this PR, the only way we tested the streaming API was...
1. By closing streams with `WriteLast()`, not `WritesDone()`.
2. By closing streams after replies have arrived, not before.
3. By sending two requests, no fewer.
Varying each of these dimensions exposed (combinations of) concurrency bugs that would result in the stream failing to be closed properly.
For example: if two requests were enqueued and `WritesDone()` was called before any replies had arrived, then code in `client.h::WritesDone()` would (correctly) avoid calling `stream_->WritesDone()`, since `write_callback_` would still have another `stream_->Write()` to do. However, the `write_callback_` would fail to perform the omitted `stream_->WriteLast()` or `stream_->WritesDone()` later, skipping straight to …

Fix a family of concurrency bugs

---

.bazelrc
BUILD.bazel
stout/grpc/client.h
stout/grpc/server.h

Before this PR, the following code would compile, and would in fact run without obvious errors:
```c++
std::mutex m;
m.lock();
m.unlock();
m.unlock(); // UNDEFINED BEHAVIOR! RACE CONDITIONS! DRAGONS!
```
This type of error was occurring at `client.h` line `340`, where we MAY do a double unlock on a mutex that was previously unlocked at line `329`. It also happened at `server.h` line `671`.
We happened to spot this issue by code inspection this time, but we should avoid making similar mistakes in the future.
While `std::mutex` can't help us much, Google's `absl::Mutex` will help us catch this class of error automatically: it'll produce a compile-time warning for many types of invalid-mutex-use, including double-lock, double-unlock, potential deadlocks, ...; this PR also upgrades those …

Fix mutex usage bugs, and prevent recurrence

---

bazel/repos.bzl

Update commit hash in repos.bzl to reflect recent changes. In particular
the version bump of grpc from 1.35 to 1.40 as well as a number of bug
fixes for concurrency.

Update commit hash in repos.bzl

---

bazel/repos.bzl

Fix broken build due to missing comma in Bazel file on line 46.
Also auto-formats the file with buildifier, which makes a few more NOOP changes.

Fix broken build due to missing comma in Bazel file.

---

bazel/repos.bzl
stout/grpc/client.h

As documented in #12, we were calling `Finish()` too early - we shouldn't call it before BOTH reads AND writes are done.
This PR corrects that problem.
It increases the number of times we lock a Mutex, but the increase is O(1): we lock once more at start-time, and once more for both writes-finish and reads-finish time. Small price to pay for avoiding persnickety bugs that come with not using your APIs as you're supposed to. 😄 
Fixes #12

Only call `stream_->Finish()` after BOTH reads AND writes are done.

---

.github/workflows/check_format_code.yml

This .yml file helps to verify that a repo's formatting matches our
specifications (`.clang-format` file in the root directory), but doesn't
automatically fix any issues.
For now I need to figure out how to make this action automatically
check if every line of the code exceeds 80 characters.

Added code_format_check.yml

---

.github/workflows/windows.yml

We do need to run this step since there was an update. You can check this on
the link below:
https://github.com/actions/virtual-environments/commit/a908240ead0632d98143582e0cdea014ee28629f

Remove llvm step

---

test/BUILD.bazel

The test in this file fails on Ubuntu  every time github actions run. For now I
will comment this file. Also I created an issue and in future I will try to fi-
gure out the reason why this test fails.

Comment `broadcast-cancel.cc` in `BUILD.bazel`

---

.gitmodules
WORKSPACE.bazel
eventuals/grpc/server.cc
eventuals/grpc/server.h
protoc-gen-eventuals/templates/eventuals.cc.j2
protoc-gen-eventuals/templates/eventuals.h.j2
test/helloworld.eventuals.cc
test/helloworld.eventuals.h

Replaces the functionality in 'Endpoint' with the generic 'eventuals::Pipe' that was specifically inspired by this code.

Use 'eventuals::Pipe' in 'Endpoint'

---

.github/workflows/ubuntu.yml

This PR removes redundant step in the `ubuntu.yml`.
Why? The answer is the following: check [this](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md).
As you can see from the link above we already have preinstalled Clang on Ubuntu 20.04, that's why `KyleMayes/install-llvm-action` is not relevant for us.

Remove redundant GitHub action's step

---

.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

Since we've renamed the grpc's repo for being `eventuals-grpc` we need to update this names in GitHub actions too.

Rename old repo

---

.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

Commits that only affect markdown files shouldn't affect the result of
any builds or tests: skip build-and-test actions on commits that only
touch markdown files.
This should vastly reduce the time it takes to merge documentation PRs
into main, and it will also avoid wasting compute running tests on no-op
commits.
Inspired by https://github.com/3rdparty/eventuals/pull/168.

Skip build-and-test hooks for markdown commits

---

test/client-death-test.cc
test/server-death-test.cc

The former prints more useful error messages containing both values. See
https://github.com/google/glog#check-macros.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61)

Cleanup: prefer CHECK_EQ(a, b) to CHECK(a == b)

---

eventuals/grpc/server.cc
test/unary.cc

Doing so will cause the program to abort. This currently can be
manifested by explicitly because the destructor for an
'eventuals::grpc::Server' might call 'Wait()' after it was already
called explicitly.

Ensure we don't call 'Wait()' on a 'grpc::Server' more than once

---

.bazelrc

Similar to https://github.com/reboot-dev/respect/pull/70, this adds a `--config=asan` build mode to eventuals-grpc.
It updates the dev-tools submodule to get the latest changes to `.bazelrc` which create the asan config.

Add asan to eventuals-grpc via dev-tools

---

.gitignore

This adds bazel-eventuals-grpc to the ignore list, as well as any other
similar auto-generated directories that get added later.

Ignore all bazel output directories

---

.gitmodules

To make it easier to pick up changes in submodules I suggest to pin each at main by default.

Pin submodules to branch main

---

test/BUILD.bazel
test/cancelled-by-client.cc
test/cancelled-by-server.cc
test/client-death-test.cc
test/deadline.cc
test/death-client.cc
test/death-server.cc
test/greeter-server.cc
test/main.cc
test/multiple-hosts.cc
test/server-death-test.cc
test/server-unavailable.cc
test/streaming.cc
test/test.h
test/unary.cc
test/unimplemented.cc

Before this commit we tried to perform the death part of the client or
server death tests in the forked child process created from
'ASSERT_DEATH()'. This has "worked" but investigating ongoing flaky
tests suggests this approach is insufficient. This commit does less in
the forked child by immediately doing an 'exec*()'.

Use 'exec*()' to perform client and server death tests

---

.github/workflows/build_and_test.yml
.gitignore
Dockerfile.dazel
WORKSPACE

Before this PR this repo could only build if you had (the
right version of) `bazel` installed on your machine. To be more hermetic
we'd like to avoid this hope-you-installed-it-right type situations. In
fact, our GitHub Codespaces don't (currently) install `bazel` at all!
This PR adds a symlink to our standard `Dockerfile.dazel` in
the `dev-tools` subrepo, allowing us to use `dazel` to build in a
repeatable way. Dazel will, unfortunately, look for a `WORKSPACE` file
instead of a `WORKSPACE.dazel` file, so we add a symlink to that also.
This is a step towards reboot-dev/company#34
While we're here, also pull in a recent version of
`submodules/eventuals`.

Add Dazel configuration

---

.github/workflows/build_and_test.yml

Modified pipeline to use remote cache located in Google Cloud Storage with Google credentials.
Google credentials are stored in GitHub organization secrets.

Add remote cache support
